<?php $properties["fprops"]=array(
array('name'=>'name','label'=>'name','type'=>'text','size'=>'200','srcName'=>'name','ufname'=>'_name','qname'=>'livret_pdf_name','multiLines'=>false,'onSubmitCheck'=>"checkText('%3\$s',%1\$s.%2\$s,%4\$s)",),);
$properties["falias"]=array('name'=>'name','_name'=>'name',);
$properties['frole']=array();
$properties['rprops']=array('name'=>'livret_pdf.search','table'=>'_livret_pdf');
 ?>